### ISSUE TITLE
4 - Interest: adding interest

### ISSUE THREAD

**Issue by shaunkatona** [decentralisedkev/SmartContractChallenges#3]
I'm not clear on this requirement:

`- For every minute that the initial balance is in the contract, the amount increases by one percent.`

As far as I can tell, this would require a 3rd party (Oraclize, Ethereum Alarm Clock, etc.) or a manual call to a `addInterest()` method.  What am I not understanding?

Additionally, what does `amount increases by one percent` mean?  Where does the increase in ether come from?  The owner again?  Is `amount` just a fake value/property on the contract or are we really using the contract balance?

**Comment by kevaundray** [comment]
Hi Shaun, 

So because we cannot increment the contract balance without paying it in. The amount has to be fake.

I may have not been very clear on that requirement. 

For the time, I should have also stated that you should not use an Oracle to dispel any confusion.

The time will be calculated using the block timestamp, which can be accessed using 'now'. The difference in time between the last now and the current now will be the time difference. I understand that this time is set by the miner and although it is not accurate, it is deterministic. Thanks for the heads up, I will edit the requirements so that it is understandable.

I hope that this has helped

**Comment by shaunkatona** [comment]
I'm still unclear on the 1% for every minute part:

_For every minute that the initial balance is in the contract, the amount increases by one percent._

When exactly do you expect that compounding calculation to occur?  The text implies every minute, but the stipulation that no 3rd party contract/timing service can be used means we must trigger this calculation manually.

Should it go in the withdraw method? If so, before or after the transfer?  If not, then in a discrete compoundInterest() method that will be called externally every minute?
